version: '3'

services:

  mysql-scc-user-service:
    image: "mysql:5.7"
    restart: always
    environment:
      - MYSQL_DATABASE=scc_users
      - MYSQL_ROOT_PASSWORD=root
    networks:
      scc:

  scc-service-registry:
    image: "scc-service-registry:latest"
    ports:
      - 8761:8761
    networks:
      scc:

  mysql-python-test:
    image: "mysql:5.7"
    restart: always
    environment:
    - MYSQL_DATABASE=python_test
    - MYSQL_ROOT_PASSWORD=root
    networks:
      scc:

  scc-user-service:
    image: "scc-user-service:latest"
    networks:
      scc:
    depends_on:
      - mysql-scc-user-service
      - scc-service-registry
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:mysql://mysql-scc-user-service:3306/scc_users?useSSL=false"
      - "SPRING_DATASOURCE_PASSWORD=root"
      - "EUREKA_URI=http://scc-service:password@scc-service-registry:8761/eureka"

  scc-api-gateway:
    image: "scc-api-gateway:latest"
    ports:
      - 80:8762
    depends_on:
      - scc-service-registry
    environment:
      - "EUREKA_URI=http://scc-service:password@scc-service-registry:8761/eureka"
    networks:
      scc:

  python-test-service:
    image: "python-test:latest"
    networks:
    - scc
    depends_on:
    - mysql-python-test
    - scc-service-registry
    environment:
    - "SPRING_DATASOURCE_URL=jdbc:mysql://mysql-python-test:3306/python_test?useSSL=false"
    - "SPRING_DATASOURCE_PASSWORD=root"
    - "EUREKA_URI=http://scc-service:password@iamtrent.de:8761/eureka"

  scc-frontend-service:
    image: "scc-frontend-service:latest"
    ports:
    - 9123:9123
    networks:
      scc:
    depends_on:
    - scc-service-registry
    environment:
    - "EUREKA_URI=http://scc-service:password@scc-service-registry:8761/eureka"

networks:
  scc:
    driver: bridge
