spring:
  application:
    name: frontend-service

server:
  port: 9123
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: tomcat

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://ilma-smart-service:password@localhost:8761/eureka} # The URI where the Eureka service registry runs.
  instance:
    preferIpAddress: true

configuration:
  cors:
    allowedOrigins:
      - http://localhost:9123
      - http://localhost
      - http://dude.iamtrent.de
      - https://dude.iamtrent.de
      - https://iamtrent.de
      - http://iamtrent.de
      - http://localhost:3000
      - http://localhost:3001