spring:
  application:
    name: frontend-service

server:
  port: 9123

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://ilma-smart-service:password@localhost:8761/eureka} # The URI where the Eureka service registry runs.
  instance:
    preferIpAddress: true

configuration:
  cors:
    allowedOrigins:
      - http://localhost:9123
      - http://localhost:3000
      - http://localhost:3001