spring:
  application:
    name: api-gateway

server:
  port: 8762

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://scc-service:password@localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"

zuul:
  sensitiveHeaders: Cookie,Set-Cookie        
  routes:
    ui:
      path: /ui/**
      serviceId: frontend-service
      stripPrefix: true        
      
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000

hystrix:  
  command:
    default:
      execution:
        timeout:
          enabled: false
