server:
  port: 8761
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: tomcat
security:
  basic:
    enabled: true
spring:
  application:
    name: service-registry
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://ilma-smart-service:password@localhost:8761/eureka}
  server:
    waitTimeInMsWhenSyncEmpty: 0