server:
  port: 8761
security:
  basic:
    enabled: true
spring:
  application:
    name: service-registry
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://ilma-smart-service:password@localhost:8761/eureka}
  server:
    waitTimeInMsWhenSyncEmpty: 0